language: android

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository
    - android-24
    - sys-img-armeabi-v7a-android-24

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - android list targets
  - echo no | android create avd --force -n test -t android-24 --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - wget http://dl.google.com/android/ndk/android-ndk32-r10-linux-x86_64.tar.bz2
  - tar -xf android-ndk32-r10-linux-x86_64.tar.bz2
  - export PATH=$PATH:$PWD/android-ndk-r10

before_script:
  - ./ci/wait_for_emulator.sh

script: ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./ci/release.sh
